### ISSUE TITLE
Nice work, would you like put the preprint on the arxiv？

### ISSUE THREAD

**Issue by Gatsby23** [dhchung/nv_liom#1]

**Comment by dhchung** [comment]
Thank you for your interest! We are considering it, but not sure right now.

**Comment by Gatsby23** [comment]
> Thank you for your interest! We are considering it, but not sure right now.

Thank you for your quick replay! If you have put it on the arxive, please give a cick on this issue.

**Comment by dhchung** [comment]
Of course :) I will let you know.

**Comment by chengwei0427** [comment]
Hi， @dhchung 
Nice work！
Maybe you can consider putting some test data for everyone to test.

**Comment by dhchung** [comment]
@chengwei0427 Thank you! I am actually considering to release the datasets (maybe as a dataset paper) after this work, but I will definitely consider to upload some small test dataset :)

**Comment by dhchung** [comment]
@Gatsby23 The preprint is out! https://arxiv.org/abs/2405.12563
I will leave the issue opened until the sample dataset is uploaded

**Comment by CharlieV5** [comment]
> @Gatsby23 The preprint is out! https://arxiv.org/abs/2405.12563 I will leave the issue opened until the sample dataset is uploaded

A little bug in the article is that the "DLIO" is short for Direct lidar-inertial odometry in the 14th reference, not Deep-Learning Inertial Odometry

**Comment by dhchung** [comment]
@CharlieV5 Indeed, I just figured it out. I have no idea why I wrote it like that. Thank you for pointing it out!
