### ISSUE TITLE
livox support?

### ISSUE THREAD

**Issue by lonlonago** [dhchung/nv_liom#2]
Hello Thank you for your work！

I want to ask whether Livox lidar is supported. If so, can you provide a config file of Livox？

In addition, I want to ask whether it is possible to set only the LIO function in the configuration file, because my data has no visual image data.

Thanks again!

**Comment by dhchung** [comment]
Hi. I tested Livox LiDAR, but it's not working well since this project is targeted on spinning type LiDARs (such as Ouster, Velodyne, others). I am planning to add some more modules to make it work with Livox LiDARs. Also, this algorithm does not use any images to process. It uses depth images, which is processed with the LiDAR data.

**Comment by lonlonago** [comment]
> Hi. I tested Livox LiDAR, but it's not working well since this project is targeted on spinning type LiDARs (such as Ouster, Velodyne, others). I am planning to add some more modules to make it work with Livox LiDARs. Also, this algorithm does not use any images to process. It uses depth images, which is processed with the LiDAR data.

depth images from ouster lidar itself or you derived from lidar data?

**Comment by dhchung** [comment]
The depth image is derived from the LiDAR point cloud data.

**Comment by lonlonago** [comment]
thank you very much!

**Comment by Youngmh1** [comment]
Hey, thanks for your awesome open-source work! Can't wait to see the version for the Livox LiDAR series.

**Comment by Youngmh1** [comment]
Hey handsome author!, when will you be able to support Livox lidar? I'm eagerly looking forward to it. I have encountered similar scenarios that need to be addressed.

**Comment by dhchung** [comment]
@Youngmh1 Hello handsome! Thank you for your interest in my project. I'm sorry but its quite hard to say since I have graduated and doing another project 😢

**Comment by Youngmh1** [comment]
> [@Youngmh1](https://github.com/Youngmh1) Hello handsome! Thank you for your interest in my project. I'm sorry but its quite hard to say since I have graduated and doing another project 😢

Anyway, thank you for this work. I’ll try to make some changes!
